config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to:'homes#top'
  get 'about' => 'homes#about'
  resources :books, only: [:new, :create, :index, :show, :destroy]
  
  
  resources :users,only:[:index,:show,:edit,:update]

  
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

belongs_to :user



end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books,dependent: :destroy
  attachment :profile_image
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
  
  
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def new
    @book = Book.new
  end
  

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @book.save
    redirect_to books_path
    
  end

  def index
    @book = Book.new
    @books = Book.all
  end
  

  def show
    @book = Book.find(params[:id])
  end
  

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title,:body)
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def about
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def index
    @book = Book.new
    @users = User.all
  end
  
  def show
    @user = User.find(params[:id])
    @books = @user.books.page(params[:page]).reverse_order
  end
  
  def edit
   @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user.id)
    
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name,:profile_image)
  end
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/index.html.erb
<% @books.each do |book| %>
<div>
  <%= link_to book_path(book.id) do %>
    <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
    <p><%= book.title %></p>
    <p><%= book.body %></p>
  <% end %>
</div>
<% end %>





<%= form_with model:@book, local:true do |f| %>

  <div class="field">
    <div><%= f.label :title, 'Title' %></div>
    <div><%= f.text_field :title %></div>
  </div>
  

 <div class="field">
   <div><%= f.label :title, 'Opinion' %></div>
   <div><%= f.text_area :body %></div>
 </div>
 
 
 <div class="action">
   <%= f.submit 'Create Book' %>
 </div>
 
 <% end %>

app/views/books/new.html.erb
<%= form_with model:@book, local:true do |f| %>

  <div class="field">
    <div><%= f.label :title, 'Title' %></div>
    <div><%= f.text_field :title %></div>
  </div>
  

 <div class="field">
   <div><%= f.label :title, 'Opinion' %></div>
   <div><%= f.text_area :body %></div>
 </div>
 
 
 <div class="action">
   <%= f.submit 'Create Book' %>
 </div>
 
 <% end %>
 

app/views/books/show.html.erb
<div class="book-body">
  <h2>Book detail</h2>
  <p><%= @book.user.name %></p>
  <%= attachment_image_tag @book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
  <p><%= @book.title %></p>
  <p><%= @book.body %></p>
   <% if @book.user == current_user %>
    <%= link_to "delete", book_path(@book), method: :delete %>
  <% end %>
</div>

app/views/homes/about.html.erb
<main>
  <p id="notice"></p>
  <div class='container'>
    <div class='row'>
      <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
    </div>
  </div>
</main>
<footer>
  <div class='container mt-5'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/homes/top.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
        <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
        <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
        <p>you can share and exchange  your opinions , inpressions , and emotions</p>
        <p> about various books!</p>
        <div class="btn-wrapper col-10 mx-auto">
          <div class="row">
            <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
          </div>
          <div class="row">
            <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>

<footer>
  <div class='container mt-5'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark"> 
        <div class="container"> 
          <a class="navbar-brand" href="/"><span>Bookers</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <% if user_signed_in? %>
              <li><%= link_to "logout", destroy_user_session_path, method: :delete %></li>
              <li><%= link_to 'Home', user_path(current_user.id) %></li>
              <li><%= link_to 'Books', books_path%></li>
              <li><%= link_to 'Users', users_path%></li>
            <% else %>
              <ul class="navbar-nav ml-auto">
                <li><%= link_to " Home", "/",class:'fas fa-home nav-link text-light' %></li>
                <li><%= link_to " About", about_path,class:'fas fa-link nav-link text-light' %></li>
                <li><%= link_to " sign up", new_user_registration_path,class:'fas fa-user-plus nav-link text-light'%></li>
                <li><%= link_to " login", new_user_session_path,class:'fas fa-sign-in-alt nav-link text-light' %></li>
              </ul>
            <% end %>
          </div>
        </div>
      </nav>  
    </header> 

     
      <%= yield %>
  </body>
    
</html>

app/views/users/edit.html.erb
<h2>User info</h2>
<%= form_with model:@user, local:true do |f| %>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
  
  <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg"%>
  <label for="inputImage">ProfileImage</label>
  <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %>
  
  <%= f.submit "Update User" %>
<% end %>

app/views/users/index.html.erb
<% @users.each do |user| %>
<div>
    <%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>
    <p><%= user.name %></p>
    <%= link_to 'Show', user_path(user.id) %>
</div>
<% end %>

app/views/users/show.html.erb
<h2>Books</h2>

<div class="profile-container">
  <h3 class="profile-name"><%= @user.name %></h3>
  <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
  <% if @user.id == current_user.id %>
    <p><%= link_to "プロフィール編集", edit_user_path(@user) %></p>
  <% end %>
  

<% @books.each do |book| %>
<div>
  <%= link_to book_path(book.id) do %>
    <p><%= book.title %></p>
  <% end %>
  
  <p><%= book.body %></p>
</div>
<% end %>